// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc_update_user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_278f8f8dd80281ef, []int{0}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UpdateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_278f8f8dd80281ef, []int{1}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateUserRequest)(nil), "pb.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "pb.UpdateUserResponse")
}

func init() { proto.RegisterFile("rpc_update_user.proto", fileDescriptor_278f8f8dd80281ef) }

var fileDescriptor_278f8f8dd80281ef = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x69, 0xad, 0xd2, 0x8e, 0x27, 0x83, 0xc2, 0x52, 0x3d, 0x48, 0x11, 0xf1, 0x94, 0x85,
	0x0a, 0xfd, 0x00, 0xe2, 0x59, 0xa4, 0xd8, 0x8b, 0x97, 0x90, 0xec, 0x8e, 0xbb, 0x8b, 0xc9, 0x66,
	0xcc, 0x24, 0x78, 0xf3, 0xb3, 0x4b, 0xb2, 0xf8, 0xe7, 0xf8, 0x7b, 0xbf, 0x97, 0x3c, 0x06, 0x2e,
	0x02, 0x35, 0x2a, 0x51, 0xab, 0x23, 0xaa, 0xc4, 0x18, 0x24, 0x05, 0x1f, 0xbd, 0x98, 0x93, 0x59,
	0xc3, 0x1f, 0x6f, 0xbe, 0xe0, 0xec, 0x50, 0x4a, 0x07, 0xc6, 0xb0, 0xc7, 0x8f, 0x84, 0x1c, 0xc5,
	0x1a, 0x96, 0xb9, 0x32, 0x6a, 0x87, 0xd5, 0xec, 0x7a, 0x76, 0xb7, 0xda, 0xff, 0xb2, 0xb8, 0x84,
	0xd5, 0x5b, 0xb2, 0x56, 0x15, 0x39, 0x9f, 0x64, 0x0e, 0x9e, 0xb2, 0x3c, 0x87, 0x63, 0x74, 0x7a,
	0xb0, 0xd5, 0x51, 0x11, 0x13, 0xe4, 0xef, 0x48, 0x33, 0x7f, 0xfa, 0xd0, 0x56, 0x8b, 0xe9, 0xc5,
	0x0f, 0x6f, 0xb6, 0x20, 0xfe, 0xef, 0x33, 0xf9, 0x91, 0x51, 0x5c, 0xc1, 0x22, 0x0f, 0x96, 0xf1,
	0xd3, 0xed, 0x52, 0x92, 0x91, 0xc5, 0x97, 0xf4, 0xe1, 0xf6, 0xf5, 0xa6, 0x1b, 0x62, 0x9f, 0x8c,
	0x6c, 0xbc, 0xab, 0x5f, 0x7a, 0x7c, 0x7c, 0xde, 0xed, 0x6a, 0x1e, 0x1c, 0x59, 0x54, 0x46, 0x8f,
	0xef, 0xaa, 0xf3, 0x35, 0x19, 0x73, 0x52, 0x4e, 0xbc, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd6,
	0xca, 0xef, 0x4c, 0x0b, 0x01, 0x00, 0x00,
}
